### ISSUE TITLE
Have the encoder/decoder own the Writer/Reader

### ISSUE THREAD

**Issue by lu-zero** [PistonDevelopers/y4m#14]
The current structures are quite unwieldy once you start having a little more complex use-cases.

**Comment by neithanmo** [comment]
I am facing the same limitation, integrating the encoder in a context in which I need to take ownership of the encoder and buffer, the current approach is useful for some use cases though, but having both options would be great.

**Comment by fintelia** [comment]
Since there is a blanket implementation of `Write` for `&mut Write`, it would actually just be enough to have the owning version. If anyone wanted to pass a reference instead it would just work.
