### ISSUE TITLE
Move to image-rs

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/y4m#18]
https://github.com/image-rs

**Comment by Kagami** [comment]
I'm ok with that.

But GitHub doesn't allow me to do it:

>Transfer ownership
>Organization members cannot transfer repositories

**Comment by bvssvni** [comment]
I will transfer the ownership in 24 hours, unless there are any objections.

**Comment by bvssvni** [comment]
Transferred.

**Comment by Kagami** [comment]
Thanks. Should we also:

```
cargo owner -r github:pistondevelopers:publish
cargo owner -a github:image-rs:publish
```

I am unable to do that too.

**Comment by bvssvni** [comment]
I've added the Publish team, removed the Piston Publish team.

**Comment by bvssvni** [comment]
I'm inviting @HeroicKatora and @fintelia as owners, so there are two private owners in case anything unexpected happens when I remove myself.

**Comment by Kagami** [comment]
Thanks.
