### ISSUE TITLE
No protection against OoM on large width or height

### ISSUE THREAD

**Issue by YaLTeR** [PistonDevelopers/y4m#20]
As soon as a `Decoder` is constructed it reads in the width and the height and tries to allocate a buffer for the frame. This means that if the width or the height are too large and cause the allocation to fail, the application panics. I don't see a way to prevent this as a library user short of wrapping it in a `catch_unwind()`. Perhaps a maximum width and height setting could be added, so `Decoder::new` can return an error instead of OoM-panicking? Alternatively, maybe the buffer should be allocated when the first frame is read in so the user has the chance to check width and height?

**Comment by Kagami** [comment]
I like the second option more because it doesn't require extra configuration for Decoder which is kinda user-specific. Though if we allocate vector only on first frame that would cause delay and might be not optimal in some use cases. Maybe we could introduce additional `force_alloc` method though which would allocate that buffer right away.

Or maybe we should provide a way to specify custom vector allocator?

Thoughts?

**Comment by 197g** [comment]
A `Limits` struct does not require the user to guess which operations are performed internally. It also doesn't require extra consideration of color types, encoding, .. which I would see as a responsibility of the library. [See png for prior art](https://docs.rs/png/0.15.0/png/struct.Limits.html).

**Comment by Kagami** [comment]
I like the limit bytes option. Should be pretty easy to implement and use.
@YaLTeR thoughts?

**Comment by YaLTeR** [comment]
That should work nicely, yeah.

**Comment by 197g** [comment]
Additional note: There is current ongoing discussion in wg-secure-code about avoiding issues with the exact calculation of resource usage, such as from overflows. Someone linked [this, not quite mature, crate](https://docs.rs/balloc/0.2.0/balloc/) for a bounded allocation vector alternative. Just to make you aware that this will likely not be the end of the story but it probably not yet the time to switch to using that internally.

**Comment by Kagami** [comment]
I've implemented option suggested by @HeroicKatora and published 0.3.4. Please try it.
