### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by astraw** [PistonDevelopers/y4m#35]
Hi, it would be great to publish the next release (0.8.0, I guess) now that we have a couple new API features which I'd like to depend on. Thanks again for this great crate!

**Comment by shssoichiro** [comment]
It would also be nice to get a new version so we can eliminate the warning about future rustc incompatibilities, which it does look like is fixed in master.

**Comment by barrbrain** [comment]
@Kagami I echo the thankfulness for this very handy crate. Much appreciated by the rav1e contributors.

**Comment by Kagami** [comment]
Published v0.8.0. Thanks for heads up!
