### ISSUE TITLE
compile with rav1e

### ISSUE THREAD

**Issue by spacexnasa** [PistonDevelopers/y4m#37]
rav1e]# cargo report future-incompatibilities --id 2 --package y4m@0.7.0
The following warnings were discovered during the build. These warnings are an
indication that the packages contain code that will become an error in a
future release of Rust. These warnings typically cover changes to close
soundness problems, unintended or undocumented behavior, or critical problems
that cannot be fixed in a backwards-compatible fashion, and are not expected
to be in wide use.

Each warning should contain a link for more information on what the warning
means and how to resolve it.

To solve this problem, you can try the following approaches:

- If the issue is not solved by updating the dependencies, a fix has to be
implemented by those dependencies. You can help with that by notifying the
maintainers of this problem (e.g. by creating a bug report) or by proposing a
fix to the maintainers (e.g. by creating a pull request):

  - y4m@0.7.0
  - Repository: https://github.com/image-rs/y4m.git
  - Detailed warning command: `cargo report future-incompatibilities --id 2 --package y4m@0.7.0`

- If waiting for an upstream fix is not an option, you can use the `[patch]`
section in `Cargo.toml` to use your own version of the dependency. For more
information, see:
https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section
        
The package `y4m v0.7.0` currently triggers the following future incompatibility lints:
> warning: trailing semicolon in macro used in expression position
>    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/y4m-0.7.0/src/lib.rs:110:42
>     |
> 110 |         return Err(Error::ParseError($p));
>     |                                          ^
> ...
> 155 |         parse_error!(ParseError::General)
>     |         --------------------------------- in this macro invocation
>     |
>     = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
>     = note: for more information, see issue #79813 <https://github.com/rust-lang/rust/issues/79813>
>     = note: macro invocations at the end of a block are treated as expressions
>     = note: to ignore the value produced by the macro, add a semicolon after the invocation of `parse_error`
>     = note: `#[allow(semicolon_in_expressions_from_macros)]` on by default
>     = note: this warning originates in the macro `parse_error` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> warning: trailing semicolon in macro used in expression position
>    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/y4m-0.7.0/src/lib.rs:110:42
>     |
> 110 |         return Err(Error::ParseError($p));
>     |                                          ^
> ...
> 183 |             parse_error!(ParseError::General)
>     |             --------------------------------- in this macro invocation
>     |
>     = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
>     = note: for more information, see issue #79813 <https://github.com/rust-lang/rust/issues/79813>
>     = note: macro invocations at the end of a block are treated as expressions
>     = note: to ignore the value produced by the macro, add a semicolon after the invocation of `parse_error`
>     = note: `#[allow(semicolon_in_expressions_from_macros)]` on by default
>     = note: this warning originates in the macro `parse_error` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> warning: trailing semicolon in macro used in expression position
>    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/y4m-0.7.0/src/lib.rs:110:42
>     |
> 110 |         return Err(Error::ParseError($p));
>     |                                          ^
> ...
> 329 |             parse_error!(ParseError::InvalidY4M)
>     |             ------------------------------------ in this macro invocation
>     |
>     = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
>     = note: for more information, see issue #79813 <https://github.com/rust-lang/rust/issues/79813>
>     = note: macro invocations at the end of a block are treated as expressions
>     = note: to ignore the value produced by the macro, add a semicolon after the invocation of `parse_error`
>     = note: `#[allow(semicolon_in_expressions_from_macros)]` on by default
>     = note: this warning originates in the macro `parse_error` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> warning: trailing semicolon in macro used in expression position
>    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/y4m-0.7.0/src/lib.rs:110:42
>     |
> 110 |         return Err(Error::ParseError($p));
>     |                                          ^
> ...
> 374 |             parse_error!(ParseError::General)
>     |             --------------------------------- in this macro invocation
>     |
>     = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
>     = note: for more information, see issue #79813 <https://github.com/rust-lang/rust/issues/79813>
>     = note: macro invocations at the end of a block are treated as expressions
>     = note: to ignore the value produced by the macro, add a semicolon after the invocation of `parse_error`
>     = note: `#[allow(semicolon_in_expressions_from_macros)]` on by default
>     = note: this warning originates in the macro `parse_error` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> warning: trailing semicolon in macro used in expression position
>    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/y4m-0.7.0/src/lib.rs:110:42
>     |
> 110 |         return Err(Error::ParseError($p));
>     |                                          ^
> ...
> 401 |             parse_error!(ParseError::InvalidY4M)
>     |             ------------------------------------ in this macro invocation
>     |
>     = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
>     = note: for more information, see issue #79813 <https://github.com/rust-lang/rust/issues/79813>
>     = note: macro invocations at the end of a block are treated as expressions
>     = note: to ignore the value produced by the macro, add a semicolon after the invocation of `parse_error`
>     = note: `#[allow(semicolon_in_expressions_from_macros)]` on by default
>     = note: this warning originates in the macro `parse_error` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> warning: trailing semicolon in macro used in expression position
>    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/y4m-0.7.0/src/lib.rs:110:42
>     |
> 110 |         return Err(Error::ParseError($p));
>     |                                          ^
> ...
> 408 |                 parse_error!(ParseError::InvalidY4M)
>     |                 ------------------------------------ in this macro invocation
>     |
>     = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
>     = note: for more information, see issue #79813 <https://github.com/rust-lang/rust/issues/79813>
>     = note: macro invocations at the end of a block are treated as expressions
>     = note: to ignore the value produced by the macro, add a semicolon after the invocation of `parse_error`
>     = note: `#[allow(semicolon_in_expressions_from_macros)]` on by default
>     = note: this warning originates in the macro `parse_error` (in Nightly builds, run with -Z macro-backtrace for more info)
> 

cargo --version
cargo 1.68.0 (115f34552 2023-02-26)
rustup --version
rustup 1.25.2 (17db695f1 2023-02-01)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.68.0 (2c8cc3432 2023-03-06)`

centos 7.9 x64

**Comment by astraw** [comment]
Thanks for the report. This was fixed in f9484db and will be out in the next release (see #35).
