### ISSUE TITLE
Documentation dispute: C420 really same as C420mpeg2?

### ISSUE THREAD

**Issue by Artoria2e5** [PistonDevelopers/y4m#39]
The description for `Colorspace::C420mpeg2` now reads:
https://github.com/image-rs/y4m/blob/58375d69120a33e2a21320e17449e84e4de9949d/src/lib.rs#L248

However, sources that I can find disagree with this conclusion:
* https://chromium.googlesource.com/webm/libvpx/+/refs/heads/main/y4minput.c indicates that there is a half-pixel (relative to Y size) or quarter-pixel (relative to C size) displacement
* https://github.com/xiph/rav1e/blob/bc516fcd18bcc2de7f009c2837469c901f7c605f/src/bin/decoder/y4m.rs#L104 indicates that it's, well, different

I recommend changing the text to:

```
    /// 4:2:0 with alternated vertically-displaced chroma planes, 8-bit.
    C420paldv,
    /// 4:2:0 with consistently vertically-displaced chroma planes, 8-bit.
    C420mpeg2,
```

or something more specific than that, if people want to ask about "hey how alternated is that".

**Comment by astraw** [comment]
I concur. Can you submit a pull request with these changes? Thanks!
