### ISSUE TITLE
Support 10-bit y4m.

### ISSUE THREAD

**Issue by tdaede** [PistonDevelopers/y4m#9]
FFmpeg has an extension to y4m that supports 10-bit and above. rav1e will need this at some point.

I'm not sure if it's best to just return a [u8] for this or try to add methods that return [u16].

**Comment by Kagami** [comment]
I think the second option is better.

**Comment by Kagami** [comment]
Thinking a bit more, it might be preferable to get planes as raw u8 values even if bitness is more than 8. E.g. for stream copying it doesn't make sense to convert to 10-bit values back and forth.

We may later add e.g. `get_y_plane_native(&self) -> Iter<u16>` iterators which would convert to the original bitness on the fly.
